### PR TITLE
Implement log level setting

### PR DESCRIPTION
**Pull request by d-e-s-o**
This patch set implements setting of the log level used by `libnitrokey` through a new command line option, -v/--verbose.

### CODE REVIEW

**Comment by d-e-s-o** [comment]
@robinkrahl , mind giving it a review? :)

**Comment by robinkrahl** [comment]
Looks good!  I’d only like to have more details in the man page:
- use at least `-vv` to see which commands are sent to the device
- use at least `-vvv` to see the full communication with the device
- `-vvvv` is the most verbose setting
- the logging output will be on stderr

**Comment by d-e-s-o** [comment]
I'll add that. Thanks for the review!

**Comment by d-e-s-o** [comment]
The change landed in `devel`.

**Pull request closed without merging**
