### PR TITLE
Implement change-pin and unblock-pin commands

### PR DESCRIPTION
**Pull request by robinkrahl**

### CODE REVIEW

**Comment by d-e-s-o** [comment]
Change set looks awesome! Thanks for implementing this functionality @robinkrahl . I'll merge it in once the one `clippy` reported "problem" is resolved.

**Comment by robinkrahl** [comment]
The clippy report does not load for me.  Would you mind fixing the
issue?  Otherwise I’ll take care of it once I’m on a regular network
connection.

**Comment by d-e-s-o** [comment]
Hm, looking at it again, what are your thoughts in introducing a new `pin` command @robinkrahl ? Given that we have two sub-command candidates I think that may be better than polluting the root namespace with duplication.
I can make the change if you don't have the cycles, but let me know.

**Comment by d-e-s-o** [comment]
I like the idea!

**Comment by robinkrahl** [comment]
I also renamed `change` to `set` for consistency.

**Comment by d-e-s-o** [comment]
Latest changes look great, Robin! I've merged them in.

**Pull request closed without merging**
