### PR TITLE
Topic/copyright

### PR DESCRIPTION
**Pull request by d-e-s-o**

### CODE REVIEW

**Comment by d-e-s-o** [comment]
@robinkrahl as we discussed in your recent pull request, here is the change to move over to complying with REUSE. Please take a look when you get a chance.

**Comment by robinkrahl** [comment]
Great, thank you!  For full compliance with the specification, we would
have to add copyright annotations to all files (see `reuse lint` [0]),
but this is already a big improvement.

[0] https://github.com/fsfe/reuse-tool

**Comment by d-e-s-o** [comment]
Thanks for your review! I've added this information to all files, added a CI pass, and merged the change.

**Comment by robinkrahl** [comment]
Thanks for the update!  You’re probably already know that, but I just wanted to note that you can use HTML comments in markdown files instead of separate license files.

**Pull request closed without merging**
