### PR TITLE
Parse configuration file

### PR DESCRIPTION
**Pull request by robinkrahl**
This patch series reads selected options (currently no_cache and model) from a
configuration file.  This is only for discussion in #100.  As I already
implemented it, I thought I might as well share it, even if we end up using a
different approach.

### CODE REVIEW

**Comment by d-e-s-o** [comment]
Just to make sure, there is nothing you are waiting on from me here, correct @robinkrahl ?

**Comment by robinkrahl** [comment]
I’m waiting on a decision on #100 – if you want to go with this
approach, I can update the pull request with the missing documentation
etc.

**Comment by robinkrahl** [comment]
I updated the pull request – I think it could be merged now.

I made these changes to the patch series:
- Replace `app_dirs` with `directories`.  `app_dirs` has not been updated for a while, and the author did not respond to my question regarding the maintenance status.  By switching to `directories`, we lose access to system-wide configuration files, but we gain a more robust and better maintained dependency.  (Problems with `app_dirs` include that it tries to create directories even if told not to, see AndyBarron/app-dirs-rs/issues/34, and even if it supports system-wide configuration, it does not comply with the specification, see AndyBarron/app-dirs-rs/issues/12).
- Squash and re-order the commits to make the patch series more concise and to avoid unnecessary intermediate steps.
- Add a `--no-cache` option for consistency.
- Update the documentation and add an example file.
- Add a simple unit test.

**Comment by d-e-s-o** [comment]
Thank you, Robin. I hope to take a closer look tomorrow. I'll probably merge it if it looks alright.  From my perspective, it mostly comes down to technical details that differentiate the solutions and I don't have the time to experiment with alternative approaches right now.

**Comment by d-e-s-o** [comment]
Seems as if we are pulling in two version of `arrayvec` and now have a total of three mechanisms to deduce/do something based on the rustc version we work with.

**Comment by robinkrahl** [comment]
Sorry, I did not mean to close this, I was just cleaning up old branches.

> Seems as if we are pulling in two version of `arrayvec`

Ultimately, `nom` is to blame here as they use an old version of `lexical-core`, see Geal/nom/pull/1100 and Geal/nom/pull/1101.  (The pull request would not fix this as it updates `lexical-core` to 0.6, but the `arrayvec` dependency is updated in 0.7.)

> now have a total of three mechanisms to deduce/do something based on the rustc version we work with.

As far as I see, they are similar but not the same:
- `rustc_version` provides functions that are evaluated at runtime.
- `rustversion` provides macros for conditional compilation.

Which one is the third?

**Comment by d-e-s-o** [comment]
> > Seems as if we are pulling in two version of `arrayvec`
> 
> Ultimately, `nom` is to blame here as they use an old version of `lexical-core`, see [Geal/nom/pull/1100](https://github.com/Geal/nom/issues/1100) and [Geal/nom/pull/1101](https://github.com/Geal/nom/pull/1101). (The pull request would not fix this as it updates `lexical-core` to 0.6, but the `arrayvec` dependency is updated in 0.7.)

Thanks for digging. I understand, but irrespective of who's fault it is, it's still not nice and something I'd really want to avoid.

> > now have a total of three mechanisms to deduce/do something based on the rustc version we work with.
> 
> As far as I see, they are similar but not the same:
> 
> * `rustc_version` provides functions that are evaluated at runtime.
> * `rustversion` provides macros for conditional compilation.
> 
> Which one is the third?

`version_check` is what I was referring to.

**Comment by d-e-s-o** [comment]
Just noticing the update. Is this the updated pull request ready for review already, Robin?

**Comment by robinkrahl** [comment]
No, I just rebased it onto the current devel.  I’ll open a new PR with
the new implementation so that you can compare both, okay?

**Comment by d-e-s-o** [comment]
> No, I just rebased it onto the current devel. I’ll open a new PR with the new implementation so that you can compare both, okay?

Sounds good.

**Comment by d-e-s-o** [comment]
We can probably close this pull request now that v2 has been merged.

**Pull request closed without merging**
